run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for this project
  misspell:
    locale: US

issues:
  exclude-rules:
    # Ignore test files for some linters
    - path: _test\.go
      linters:
        - errcheck
    # Allow fmt.Print* in CLI code
    - path: internal/cli/
      linters:
        - forbidigo
